#!/usr/bin/env bash
# 1. Install nginx web server
sudo apt-get update
sudo apt-get upgrade
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
