#!/usr/bin/env bash
# 0. Double the number of webservers
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo chmod 777 /etc/nginx /etc/nginx/nginx.conf
sudo sed -i "/http {/ a add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
service nginx start
