#!/usr/bin/env bash
# Using what you did for task #0, make your fix short and sweet.
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx restart
sudo pkill -f nginx
