#!/usr/bin/env bash
#displays the content of the file /etc/passwd, using the while loop + IFS.
IFS=:
while read -r  USER PASS USER_ID GR_ID USERIDINFO HOME_DIR CMDSHELL
do
  echo "The user $USER is part of the $GR_ID gang, lives in $HOME_DIR and rides $CMDSHELL. $USER_ID's place is protected by the passcode $PASS, more info about the user here: $USERIDINFO"
done < /etc/passwd
