#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but in 9th interation print "Hi"
i=1
while [ $i -le 10 ]
do
  if [ $i != 9 ]
    then
	echo "Best School"
    else
	echo "Hi"
  fi
  i=$(($i + 1))
done
