#!/usr/bin/env bash
# Configure ufw so that it blocks all incoming traffic, except the following TCP ports:
# 22 (SSH)
# 443 (HTTPS SSL)
# 80 (HTTP)
apt-get install ufw -y
ufw allow ssh
ufw allow http
ufw allow https
ufw enable
